version: "3.9"
services:
  flask: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    # remove this, less save
    ports:
      - "27017:27017"